import React from 'react';
import { BookOpen, Fingerprint, Globe2, ShieldCheck, Network, LockKeyhole, ArrowUpRight } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { Link } from '../router/Router';
import { useLanguage } from '../i18n/LanguageContext';
import { SEOHead } from '../components/seo/SEOHead';

const content = {
 en:{title:'PrivaSec Privacy & Security Learning Center',desc:'Practical guides to IP privacy, browser fingerprinting, WebRTC, security headers and IP reputation.',intro:'Understand what websites can observe, what the signals mean, and how to reduce unnecessary exposure. Every guide connects to a free PrivaSec audit.',read:'Read guide',cards:[['ip','What can your IP reveal?','Public IP, ASN, geolocation, RDAP, DNS and reputation.', '/', Globe2],['fingerprint','How browser fingerprinting works','Understand entropy, signal combinations and exposure.', '/browser', Fingerprint],['webrtc','What WebRTC can reveal','Learn the difference between browser capability and a proven leak.', '/browser', Network],['headers','Security & privacy headers','HSTS, CSP, Permissions-Policy and Referrer-Policy.', '/headers', ShieldCheck],['reputation','How IP reputation works','Reports, hosting signals, confidence and limitations.', '/', LockKeyhole]]},
 ar:{title:'مركز PrivaSec للتعلم في الخصوصية والأمان',desc:'أدلة عملية عن خصوصية IP وبصمة المتصفح وWebRTC وترويسات الأمان وسمعة IP.',intro:'افهم ما الذي تستطيع المواقع ملاحظته وما تعنيه الإشارات وكيف تقلل التعرض غير الضروري. كل دليل مرتبط بفحص مجاني.',read:'قراءة الدليل',cards:[['ip','ماذا يكشف IP عنك؟','العنوان العام وASN والموقع وRDAP وDNS والسمعة.','/',Globe2],['fingerprint','كيف تعمل بصمة المتصفح؟','افهم الإنتروبيا ومجموعات الإشارات وسطح التعرض.','/browser',Fingerprint],['webrtc','ماذا يمكن أن يكشف WebRTC؟','الفرق بين قدرة المتصفح والتسريب المثبت.','/browser',Network],['headers','ترويسات الأمان والخصوصية','HSTS وCSP وPermissions-Policy وReferrer-Policy.','/headers',ShieldCheck],['reputation','كيف تعمل سمعة IP؟','التقارير والاستضافة والثقة والقيود.','/',LockKeyhole]]},
 es:{title:'Centro de aprendizaje de privacidad y seguridad de PrivaSec',desc:'Guías prácticas sobre privacidad IP, fingerprinting, WebRTC, cabeceras y reputación IP.',intro:'Comprende qué pueden observar los sitios y cómo reducir la exposición innecesaria.',read:'Leer guía',cards:[['ip','¿Qué puede revelar tu IP?','IP pública, ASN, geolocalización, RDAP, DNS y reputación.','/',Globe2],['fingerprint','Cómo funciona el fingerprinting','Entropía, señales combinadas y exposición.','/browser',Fingerprint],['webrtc','Qué puede revelar WebRTC','Diferencia entre capacidad y fuga demostrada.','/browser',Network],['headers','Cabeceras de seguridad y privacidad','HSTS, CSP, Permissions-Policy y Referrer-Policy.','/headers',ShieldCheck],['reputation','Cómo funciona la reputación IP','Informes, hosting, confianza y límites.','/',LockKeyhole]]},
 fr:{title:'Centre d’apprentissage confidentialité et sécurité PrivaSec',desc:'Guides pratiques sur la confidentialité IP, l’empreinte, WebRTC, les en-têtes et la réputation IP.',intro:'Comprenez ce que les sites peuvent observer et comment réduire l’exposition inutile.',read:'Lire le guide',cards:[['ip','Que révèle votre IP ?','IP publique, ASN, géolocalisation, RDAP, DNS et réputation.','/',Globe2],['fingerprint','Empreinte du navigateur','Entropie, signaux combinés et exposition.','/browser',Fingerprint],['webrtc','Ce que WebRTC peut révéler','Différence entre capacité et fuite démontrée.','/browser',Network],['headers','En-têtes sécurité et confidentialité','HSTS, CSP, Permissions-Policy et Referrer-Policy.','/headers',ShieldCheck],['reputation','Réputation IP','Signalements, hébergement, confiance et limites.','/',LockKeyhole]]},
 pt:{title:'Centro de aprendizado de privacidade e segurança PrivaSec',desc:'Guias práticos sobre privacidade IP, fingerprinting, WebRTC, cabeçalhos e reputação IP.',intro:'Entenda o que sites podem observar e como reduzir exposição desnecessária.',read:'Ler guia',cards:[['ip','O que seu IP pode revelar?','IP público, ASN, geolocalização, RDAP, DNS e reputação.','/',Globe2],['fingerprint','Como funciona o fingerprinting','Entropia, sinais combinados e exposição.','/browser',Fingerprint],['webrtc','O que o WebRTC pode revelar','Diferença entre capacidade e vazamento comprovado.','/browser',Network],['headers','Cabeçalhos de segurança e privacidade','HSTS, CSP, Permissions-Policy e Referrer-Policy.','/headers',ShieldCheck],['reputation','Como funciona a reputação IP','Relatórios, hospedagem, confiança e limites.','/',LockKeyhole]]},
 tr:{title:'PrivaSec Gizlilik ve Güvenlik Öğrenme Merkezi',desc:'IP gizliliği, tarayıcı parmak izi, WebRTC, güvenlik başlıkları ve IP itibarı rehberleri.',intro:'Sitelerin neleri görebileceğini ve gereksiz görünürlüğü nasıl azaltabileceğinizi öğrenin.',read:'Rehberi oku',cards:[['ip','IP adresiniz neleri gösterir?','Genel IP, ASN, konum, RDAP, DNS ve itibar.','/',Globe2],['fingerprint','Tarayıcı parmak izi','Entropi, sinyal birleşimleri ve görünürlük.','/browser',Fingerprint],['webrtc','WebRTC neleri gösterebilir?','Yetenek ile kanıtlanmış sızıntı arasındaki fark.','/browser',Network],['headers','Güvenlik ve gizlilik başlıkları','HSTS, CSP, Permissions-Policy ve Referrer-Policy.','/headers',ShieldCheck],['reputation','IP itibarı nasıl çalışır?','Raporlar, barındırma, güven ve sınırlar.','/',LockKeyhole]]}
};
type LearnCard = readonly [string, string, string, string, LucideIcon];

export const LearnRoute: React.FC = () => {
  const { language } = useLanguage();
  const c = content[language] as unknown as { title: string; desc: string; intro: string; read: string; cards: readonly LearnCard[] };
  const cards = c.cards;
  return <div className="max-w-5xl mx-auto py-8 sm:py-10 space-y-8">
    <SEOHead title={`${c.title} | PrivaSec`} description={c.desc} path="/learn" />
    <header className="rounded-3xl border border-slate-800 bg-slate-900/70 p-8 sm:p-10">
      <div className="flex gap-4 items-start"><div className="w-12 h-12 rounded-2xl border border-cyan-500/30 bg-cyan-500/10 flex items-center justify-center text-cyan-400"><BookOpen className="w-6 h-6" /></div><div><div className="text-xs uppercase tracking-[0.2em] text-cyan-400/80">PrivaSec Learn</div><h1 className="mt-2 text-3xl sm:text-4xl font-bold text-slate-100">{c.title}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">{c.intro}</p></div></div>
    </header>
    <section className="grid sm:grid-cols-2 gap-4" aria-labelledby="learn-guides">
      <h2 id="learn-guides" className="sr-only">Guides</h2>
      {cards.map(([id, title, desc, href, Icon]) => <article key={id} className="rounded-2xl border border-slate-800 bg-slate-900/55 p-5"><Icon className="w-5 h-5 text-cyan-400" aria-hidden="true"/><h2 className="mt-4 text-lg font-semibold text-slate-100">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{desc}</p><Link to={href} className="mt-4 inline-flex min-h-10 items-center gap-2 rounded-md px-2 -mx-2 text-sm font-semibold text-cyan-400 hover:text-cyan-300 hover:bg-cyan-500/5 focus:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400/70 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950 transition-colors">{c.read}<ArrowUpRight className="w-4 h-4" aria-hidden="true"/></Link></article>)}
    </section>
  </div>;
};
