import React, { useState } from 'react';
import { Globe2, ShieldCheck, Search, AlertTriangle, ExternalLink, Loader2 } from 'lucide-react';
import { useLanguage } from '../i18n/LanguageContext';
import { apiClient } from '@packages/api-client';
import type { SiteAuditResponse } from '@packages/api-contract';

export const SiteAuditRoute: React.FC = () => {
  const { language } = useLanguage();
  const [url, setUrl] = useState('');
  const [data, setData] = useState<SiteAuditResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const copy = {
    en: { title:'Website Privacy & Security Audit', sub:'Check the public HTTPS response, security headers, cookies, redirects, and visible third-party tracking signals.', placeholder:'example.com', run:'Run site audit', loading:'Auditing website…', invalid:'Enter a public HTTPS website.', limitation:'Transparent limitation: this scan fetches the page server-side but does not execute browser JavaScript.', headers:'Security headers', trackers:'Tracking signals', cookies:'Cookies', redirects:'Redirects', privacy:'Privacy', security:'Security', evidence:'Evidence', present:'Present', missing:'Missing', none:'No signature matched', failed:'Audit failed', print:'Print report', timing:'Response time', bytes:'HTML analyzed' },
    ar: { title:'تدقيق خصوصية وأمان الموقع', sub:'افحص استجابة HTTPS العامة، وترويسات الأمان، وملفات الارتباط، وإعادة التوجيه، وإشارات التتبع الظاهرة.', placeholder:'example.com', run:'بدء تدقيق الموقع', loading:'جارٍ تدقيق الموقع…', invalid:'أدخل موقع HTTPS عامًا.', limitation:'حدود واضحة: الفحص يجلب الصفحة من الخادم لكنه لا ينفذ JavaScript داخل المتصفح.', headers:'ترويسات الأمان', trackers:'إشارات التتبع', cookies:'ملفات الارتباط', redirects:'إعادة التوجيه', privacy:'الخصوصية', security:'الأمان', evidence:'الأدلة', present:'موجود', missing:'مفقود', none:'لم تُطابق أي بصمة', failed:'فشل التدقيق', print:'طباعة التقرير', timing:'زمن الاستجابة', bytes:'HTML محلل' },
    es: { title:'Auditoría de privacidad y seguridad web', sub:'Comprueba la respuesta HTTPS pública, cabeceras de seguridad, cookies, redirecciones y señales visibles de rastreo.', placeholder:'example.com', run:'Auditar sitio', loading:'Auditando sitio…', invalid:'Introduce un sitio HTTPS público.', limitation:'Limitación transparente: el escaneo obtiene la página en el servidor, pero no ejecuta JavaScript del navegador.', headers:'Cabeceras de seguridad', trackers:'Señales de rastreo', cookies:'Cookies', redirects:'Redirecciones', privacy:'Privacidad', security:'Seguridad', evidence:'Evidencia', present:'Presente', missing:'Falta', none:'Sin coincidencias', failed:'Error de auditoría', print:'Imprimir informe', timing:'Tiempo de respuesta', bytes:'HTML analizado' },
    fr: { title:'Audit de confidentialité et sécurité du site', sub:'Vérifiez la réponse HTTPS publique, les en-têtes de sécurité, les cookies, les redirections et les signaux de suivi visibles.', placeholder:'example.com', run:'Auditer le site', loading:'Audit en cours…', invalid:'Saisissez un site HTTPS public.', limitation:'Limite transparente : le scan récupère la page côté serveur mais n’exécute pas le JavaScript du navigateur.', headers:'En-têtes de sécurité', trackers:'Signaux de suivi', cookies:'Cookies', redirects:'Redirections', privacy:'Confidentialité', security:'Sécurité', evidence:'Preuves', present:'Présent', missing:'Manquant', none:'Aucune signature détectée', failed:'Échec de l’audit', print:'Imprimer le rapport', timing:'Temps de réponse', bytes:'HTML analysé' },
    pt: { title:'Auditoria de privacidade e segurança do site', sub:'Verifique a resposta HTTPS pública, cabeçalhos de segurança, cookies, redirecionamentos e sinais visíveis de rastreamento.', placeholder:'example.com', run:'Auditar site', loading:'Auditando…', invalid:'Informe um site HTTPS público.', limitation:'Limitação transparente: o servidor busca a página, mas não executa o JavaScript do navegador.', headers:'Cabeçalhos de segurança', trackers:'Sinais de rastreamento', cookies:'Cookies', redirects:'Redirecionamentos', privacy:'Privacidade', security:'Segurança', evidence:'Evidências', present:'Presente', missing:'Ausente', none:'Nenhuma assinatura encontrada', failed:'Falha na auditoria', print:'Imprimir relatório', timing:'Tempo de resposta', bytes:'HTML analisado' },
    tr: { title:'Web sitesi gizlilik ve güvenlik denetimi', sub:'Genel HTTPS yanıtını, güvenlik başlıklarını, çerezleri, yönlendirmeleri ve görünür izleme sinyallerini inceleyin.', placeholder:'example.com', run:'Siteyi denetle', loading:'Denetleniyor…', invalid:'Genel bir HTTPS sitesi girin.', limitation:'Şeffaf sınırlama: tarama sayfayı sunucuda alır ancak tarayıcı JavaScriptini çalıştırmaz.', headers:'Güvenlik başlıkları', trackers:'İzleme sinyalleri', cookies:'Çerezler', redirects:'Yönlendirmeler', privacy:'Gizlilik', security:'Güvenlik', evidence:'Kanıt', present:'Mevcut', missing:'Eksik', none:'Eşleşme bulunamadı', failed:'Denetim başarısız', print:'Raporu yazdır', timing:'Yanıt süresi', bytes:'Analiz edilen HTML' },
  }[language];

  const run = async () => {
    setError(''); setData(null); const normalized = url.trim();
    if (!normalized || !/^https?:\/\//i.test(normalized) && !/^[a-z0-9.-]+\.[a-z]{2,}(?::443)?(?:\/.*)?$/i.test(normalized)) { setError(copy.invalid); return; }
    setLoading(true);
    try { setData(await apiClient.auditSite(normalized)); } catch (e) { setError(e instanceof Error ? e.message : copy.failed); }
    finally { setLoading(false); }
  };

  return <div className="space-y-6 py-4 max-w-5xl mx-auto">
    <section className="rounded-3xl border border-slate-800 bg-slate-900/70 p-7 sm:p-9 shadow-2xl">
      <div className="flex items-start gap-4"><div className="w-12 h-12 rounded-2xl border border-cyan-500/30 bg-cyan-500/10 flex items-center justify-center text-cyan-400"><Globe2 className="w-6 h-6"/></div><div><h1 className="text-2xl sm:text-3xl font-bold text-slate-100">{copy.title}</h1><p className="text-sm text-slate-400 mt-2 max-w-2xl">{copy.sub}</p></div></div>
      <div className="mt-7 flex flex-col sm:flex-row gap-3"><input value={url} onChange={e=>setUrl(e.target.value)} onKeyDown={e=>{if(e.key==='Enter') void run();}} placeholder={copy.placeholder} className="flex-1 rounded-xl border border-slate-700 bg-slate-950/80 px-4 py-3 text-slate-100 placeholder:text-slate-600 outline-none focus:border-cyan-500" /><button onClick={()=>void run()} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-500 px-5 py-3 text-sm font-bold text-slate-950 hover:bg-cyan-400 disabled:opacity-60">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:<Search className="w-4 h-4"/>}{loading?copy.loading:copy.run}</button></div>
      {error && <div className="mt-4 flex gap-2 rounded-xl border border-rose-800/60 bg-rose-950/20 p-3 text-sm text-rose-300"><AlertTriangle className="w-4 h-4 mt-0.5 shrink-0"/>{error}</div>}
    </section>
    {data && <>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[['privacy',copy.privacy,data.scores.privacy],['security',copy.security,data.scores.security],['headers',copy.headers,data.scores.headers],['redirects',copy.redirects,data.redirectCount]].map(([k,l,v])=><div key={String(k)} className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="text-xs text-slate-500">{l}</div><div className="mt-2 text-3xl font-bold text-slate-100">{v}{k==='redirects'?'':'/100'}</div></div>)}
      </div>
      <div className="flex flex-wrap items-center gap-3 text-xs text-slate-500"><span>{copy.timing}: {data.responseTimeMs}ms</span><span>·</span><span>{copy.bytes}: {data.evidence.fetchedBytes.toLocaleString()} bytes</span><button onClick={()=>window.print()} className="ml-auto rounded-lg border border-slate-700 px-3 py-1.5 text-slate-300 hover:bg-slate-900">{copy.print}</button></div>
      <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-base font-bold text-slate-100">{copy.headers}</h2><p className="text-xs text-slate-500 mt-1">{data.finalUrl} · HTTP {data.status}</p></div><a href={data.finalUrl} target="_blank" rel="noopener noreferrer" className="text-xs text-cyan-400 inline-flex items-center gap-1">{copy.evidence}<ExternalLink className="w-3 h-3"/></a></div><div className="mt-4 grid md:grid-cols-2 gap-2">{data.headers.map(h=><div key={h.name} className="flex items-center justify-between rounded-xl border border-slate-800/70 bg-slate-950/40 px-3 py-2"><span className="font-mono text-xs text-slate-300">{h.name}</span><span className={h.present?'text-emerald-400':'text-slate-500'}>{h.present?copy.present:copy.missing}</span></div>)}</div></section>
      <div className="grid md:grid-cols-2 gap-5"><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="text-base font-bold text-slate-100">{copy.trackers}</h2><div className="mt-3 space-y-2">{data.trackers.length?data.trackers.map(t=><div key={t.host} className="flex justify-between gap-3 rounded-lg bg-slate-950/40 px-3 py-2"><span className="font-mono text-xs text-slate-300 truncate">{t.host}</span><span className="text-[11px] text-amber-300">{t.category}</span></div>):<div className="text-sm text-emerald-400">{copy.none}</div>}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-5"><h2 className="text-base font-bold text-slate-100">{copy.cookies}</h2><div className="mt-3 space-y-2">{data.cookies.length?data.cookies.map(c=><div key={c.name} className="flex items-center justify-between rounded-lg bg-slate-950/40 px-3 py-2"><span className="font-mono text-xs text-slate-300">{c.name}</span><span className="text-[11px] text-slate-400">{[c.secure&&'Secure',c.httpOnly&&'HttpOnly',c.sameSite&&'SameSite'].filter(Boolean).join(' · ')||copy.missing}</span></div>):<div className="text-sm text-emerald-400">{copy.none}</div>}</div></section></div>
      <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs text-amber-200/80">{copy.limitation}</div>
    </>}
  </div>;
};
