import React from 'react';
import { ArrowUpRight, Monitor, FileSearch, Globe2, ShieldCheck } from 'lucide-react';
import { Link } from '../../../router/Router';
import { useLanguage } from '../../../i18n/LanguageContext';

export const FreeToolsSection: React.FC = () => {
  const { language } = useLanguage();
  const c = {
    en: { title:'One audit. Four views.', sub:'Start with the complete audit, then open any specialist view for deeper evidence. Everything here is free.', ip:'IP & Network', ipd:'Geo, ASN, RDAP, DNS and reputation signals', browser:'Browser Intelligence', browserd:'Fingerprint surface, WebRTC, graphics and hardware', headers:'HTTP Headers', headersd:'Privacy, security, cookies and client-hint analysis', site:'Website Audit', sited:'HTTPS headers, cookies, redirects and static tracker signals' },
    ar: { title:'تدقيق واحد. أربع زوايا.', sub:'ابدأ بالتدقيق الكامل ثم افتح أي قسم متخصص للأدلة الأعمق. كل ذلك مجاني.', ip:'IP والشبكة', ipd:'الموقع وASN وRDAP وDNS وسمعة العنوان', browser:'ذكاء المتصفح', browserd:'سطح البصمة وWebRTC والرسوميات والعتاد', headers:'ترويسات HTTP', headersd:'الخصوصية والأمان وملفات الارتباط وClient Hints', site:'تدقيق المواقع', sited:'HTTPS والترويسات والارتباطات وإعادة التوجيه وإشارات التتبع' },
    es: { title:'Una auditoría. Cuatro vistas.', sub:'Empieza con la auditoría completa y abre cualquier vista especializada para más evidencia. Todo es gratis.', ip:'IP y red', ipd:'Geo, ASN, RDAP, DNS y reputación', browser:'Inteligencia del navegador', browserd:'Huella, WebRTC, gráficos y hardware', headers:'Cabeceras HTTP', headersd:'Privacidad, seguridad, cookies y Client Hints', site:'Auditoría web', sited:'HTTPS, cabeceras, cookies, redirecciones y señales de rastreo' },
    fr: { title:'Un audit. Quatre vues.', sub:'Commencez par l’audit complet puis ouvrez une vue spécialisée pour plus de preuves. Tout est gratuit.', ip:'IP et réseau', ipd:'Géo, ASN, RDAP, DNS et réputation', browser:'Intelligence du navigateur', browserd:'Empreinte, WebRTC, graphiques et matériel', headers:'En-têtes HTTP', headersd:'Confidentialité, sécurité, cookies et Client Hints', site:'Audit du site', sited:'HTTPS, en-têtes, cookies, redirections et signaux de suivi' },
    pt: { title:'Uma auditoria. Quatro visões.', sub:'Comece com a auditoria completa e abra uma visão especializada para mais evidências. Tudo é gratuito.', ip:'IP e rede', ipd:'Geo, ASN, RDAP, DNS e reputação', browser:'Inteligência do navegador', browserd:'Fingerprint, WebRTC, gráficos e hardware', headers:'Cabeçalhos HTTP', headersd:'Privacidade, segurança, cookies e Client Hints', site:'Auditoria do site', sited:'HTTPS, cabeçalhos, cookies, redirecionamentos e sinais de rastreamento' },
    tr: { title:'Tek denetim. Dört görünüm.', sub:'Tam denetimle başlayın, ardından daha derin kanıt için uzman görünümünü açın. Hepsi ücretsiz.', ip:'IP ve ağ', ipd:'Geo, ASN, RDAP, DNS ve itibar sinyalleri', browser:'Tarayıcı istihbaratı', browserd:'Parmak izi yüzeyi, WebRTC, grafikler ve donanım', headers:'HTTP başlıkları', headersd:'Gizlilik, güvenlik, çerezler ve Client Hints', site:'Web sitesi denetimi', sited:'HTTPS, başlıklar, çerezler, yönlendirmeler ve izleme sinyalleri' },
  }[language];
  const items = [
    [Globe2, '/', c.ip, c.ipd, 'cyan'],
    [Monitor, '/browser', c.browser, c.browserd, 'violet'],
    [FileSearch, '/headers', c.headers, c.headersd, 'blue'],
    [ShieldCheck, '/site-audit', c.site, c.sited, 'emerald'],
  ] as const;
  return <section className="space-y-4" aria-labelledby="free-tools-title"><div><h2 id="free-tools-title" className="text-xl font-bold text-slate-100">{c.title}</h2><p className="text-sm text-slate-400 mt-1">{c.sub}</p></div><div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-3">{items.map(([Icon,href,title,desc,tone])=><Link key={href} to={href} className="group rounded-2xl border border-slate-800 bg-slate-900/55 p-4 hover:border-slate-700 hover:bg-slate-900/80 transition-all"><div className="flex items-start justify-between gap-3"><div className={`w-9 h-9 rounded-xl flex items-center justify-center border ${tone==='cyan'?'bg-cyan-500/10 border-cyan-500/20 text-cyan-400':tone==='violet'?'bg-violet-500/10 border-violet-500/20 text-violet-400':tone==='blue'?'bg-blue-500/10 border-blue-500/20 text-blue-400':'bg-emerald-500/10 border-emerald-500/20 text-emerald-400'}`}><Icon className="w-4 h-4"/></div><ArrowUpRight className="w-4 h-4 text-slate-600 group-hover:text-slate-300"/></div><div className="mt-3 text-sm font-semibold text-slate-200">{title}</div><div className="text-xs leading-5 text-slate-500 mt-1">{desc}</div></Link>)}</div></section>;
};
