import type { HeaderDefinition, MissingHeaderDefinition } from './types';

/**
 * HeaderRegistry
 * Authoritative dictionary of known HTTP headers with metadata, category classification,
 * privacy impact descriptions, sensitivity flags, and security considerations.
 */
export const HEADER_DEFINITIONS: Record<string, HeaderDefinition> = {
  // --- PRIVACY & TRACKING CONTROLS ---
  'sec-gpc': {
    canonicalName: 'Sec-GPC',
    category: 'PRIVACY_TRACKING',
    description: 'Global Privacy Control signal communicating the user preference to opt out of data sharing and selling under applicable privacy regulations (such as CCPA/CPRA).',
    privacyImpact: 'Proactive privacy protection signal enabled.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isPrivacyControl: true,
    isStandard: true,
    recommendation: 'Keep Global Privacy Control enabled to signal non-consent to tracking across participating sites.',
  },
  'dnt': {
    canonicalName: 'DNT',
    category: 'PRIVACY_TRACKING',
    description: 'Legacy Do Not Track header indicating user request not to be tracked across web sites.',
    privacyImpact: 'Legacy privacy preference signal active.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isPrivacyControl: true,
    isStandard: true,
    recommendation: 'Complement DNT with modern Sec-GPC header for recognized tracker opt-out signals.',
  },
  'save-data': {
    canonicalName: 'Save-Data',
    category: 'PRIVACY_TRACKING',
    description: 'Client hint requesting reduced data usage from the server (e.g. compressed media).',
    privacyImpact: 'Discloses bandwidth-saving user preference.',
    defaultStatus: 'INFO',
    severity: 'low',
    riskPoints: 0,
    isStandard: true,
  },
  'sec-purpose': {
    canonicalName: 'Sec-Purpose',
    category: 'PRIVACY_TRACKING',
    description: 'Specifies the purpose of the request, such as prefetch or prerender.',
    privacyImpact: 'Reveals browser speculative fetching behavior.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
  },
  'purpose': {
    canonicalName: 'Purpose',
    category: 'PRIVACY_TRACKING',
    description: 'Legacy prefetch purpose header.',
    privacyImpact: 'Discloses prefetch request context.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
  },

  // --- IDENTITY & CLIENT HINTS ---
  'user-agent': {
    canonicalName: 'User-Agent',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Discloses client browser family, rendering engine, OS platform, and version architecture.',
    privacyImpact: 'Broad device, operating system, and browser version disclosure.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 2,
    isStandard: true,
    recommendation: 'Modern browsers employ User-Agent reduction to minimize entropy leaks.',
  },
  'sec-ch-ua': {
    canonicalName: 'Sec-CH-UA',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Client Hint brand list providing modern browser brand names and major versions.',
    privacyImpact: 'Discloses browser brand and major release version.',
    defaultStatus: 'INFO',
    severity: 'low',
    riskPoints: 1,
    isClientHint: true,
    isStandard: true,
  },
  'sec-ch-ua-mobile': {
    canonicalName: 'Sec-CH-UA-Mobile',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Boolean client hint indicating whether the browser is running on a mobile device.',
    privacyImpact: 'Discloses mobile vs desktop device form factor.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isClientHint: true,
    isStandard: true,
  },
  'sec-ch-ua-platform': {
    canonicalName: 'Sec-CH-UA-Platform',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Client Hint disclosing the host operating system platform (e.g. "macOS", "Windows", "Linux", "Android").',
    privacyImpact: 'Discloses operating system platform.',
    defaultStatus: 'INFO',
    severity: 'low',
    riskPoints: 1,
    isClientHint: true,
    isStandard: true,
  },
  'sec-ch-ua-platform-version': {
    canonicalName: 'Sec-CH-UA-Platform-Version',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'High-entropy Client Hint providing exact operating system kernel/patch version.',
    privacyImpact: 'High entropy OS patch and build level disclosure.',
    defaultStatus: 'WARNING',
    severity: 'medium',
    riskPoints: 4,
    isClientHint: true,
    isStandard: true,
    recommendation: 'Prevent high-entropy platform version disclosure to reduce fingerprint entropy.',
  },
  'sec-ch-ua-model': {
    canonicalName: 'Sec-CH-UA-Model',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'High-entropy Client Hint disclosing exact hardware device model (e.g. "Pixel 8 Pro", "SM-G998B").',
    privacyImpact: 'Exposes exact physical hardware device model name.',
    defaultStatus: 'WARNING',
    severity: 'high',
    riskPoints: 6,
    isClientHint: true,
    isStandard: true,
    recommendation: 'Disable model client hints in browser settings or enterprise policies.',
  },
  'sec-ch-ua-arch': {
    canonicalName: 'Sec-CH-UA-Arch',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Client Hint disclosing underlying CPU architecture (e.g. "arm", "x86").',
    privacyImpact: 'Discloses processor hardware architecture.',
    defaultStatus: 'WARNING',
    severity: 'low',
    riskPoints: 2,
    isClientHint: true,
    isStandard: true,
  },
  'sec-ch-ua-bitness': {
    canonicalName: 'Sec-CH-UA-Bitness',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Client Hint indicating CPU bitness (e.g. "64" or "32").',
    privacyImpact: 'Discloses operating system CPU bit width.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 1,
    isClientHint: true,
    isStandard: true,
  },
  'sec-ch-ua-full-version-list': {
    canonicalName: 'Sec-CH-UA-Full-Version-List',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'High-entropy Client Hint exposing exact full build and patch versions for all browser components.',
    privacyImpact: 'High entropy full browser patch string disclosure.',
    defaultStatus: 'WARNING',
    severity: 'medium',
    riskPoints: 4,
    isClientHint: true,
    isStandard: true,
  },
  'sec-ch-prefers-color-scheme': {
    canonicalName: 'Sec-CH-Prefers-Color-Scheme',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Client Hint indicating user system UI theme preference (dark or light mode).',
    privacyImpact: 'Discloses OS desktop theme preference.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isClientHint: true,
  },
  'sec-ch-prefers-reduced-motion': {
    canonicalName: 'Sec-CH-Prefers-Reduced-Motion',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Client Hint indicating whether user has requested reduced motion animations in system accessibility settings.',
    privacyImpact: 'Discloses accessibility motion preference.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isClientHint: true,
  },
  'sec-ch-viewport-width': {
    canonicalName: 'Sec-CH-Viewport-Width',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Client Hint disclosing exact viewport width in CSS pixels.',
    privacyImpact: 'Discloses screen viewport dimensions.',
    defaultStatus: 'INFO',
    severity: 'low',
    riskPoints: 2,
    isClientHint: true,
  },
  'device-memory': {
    canonicalName: 'Device-Memory',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Client Hint providing approximate client device RAM capacity in gigabytes.',
    privacyImpact: 'Discloses hardware system RAM capacity.',
    defaultStatus: 'WARNING',
    severity: 'medium',
    riskPoints: 3,
    isClientHint: true,
    isStandard: true,
  },
  'downlink': {
    canonicalName: 'Downlink',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Network Information Client Hint indicating effective downlink connection bandwidth.',
    privacyImpact: 'Discloses estimated network link speed.',
    defaultStatus: 'INFO',
    severity: 'low',
    riskPoints: 1,
    isClientHint: true,
  },
  'ect': {
    canonicalName: 'ECT',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Network Information Client Hint indicating effective network connection type (4g, 3g, 2g, slow-2g).',
    privacyImpact: 'Discloses network connection generation.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isClientHint: true,
  },
  'rtt': {
    canonicalName: 'RTT',
    category: 'IDENTITY_CLIENT_HINTS',
    description: 'Network Information Client Hint providing estimated round-trip time in milliseconds.',
    privacyImpact: 'Discloses round-trip network latency.',
    defaultStatus: 'INFO',
    severity: 'low',
    riskPoints: 1,
    isClientHint: true,
  },

  // --- PROXY & NETWORK HEADERS ---
  'x-forwarded-for': {
    canonicalName: 'X-Forwarded-For',
    category: 'PROXY_NETWORK',
    description: 'De-facto standard header for identifying the originating IP address of a client connecting through an HTTP proxy or load balancer.',
    privacyImpact: 'Exposes intermediate or origin client IP address chain.',
    defaultStatus: 'WARNING',
    severity: 'high',
    riskPoints: 10,
    isProxyHeader: true,
    isStandard: false,
    recommendation: 'If using an anonymizing VPN, ensure proxy headers do not leak your origin network IP.',
  },
  'x-forwarded-proto': {
    canonicalName: 'X-Forwarded-Proto',
    category: 'PROXY_NETWORK',
    description: 'Identifies the protocol (HTTP or HTTPS) that a client used to connect to your proxy or load balancer.',
    privacyImpact: 'Discloses origin transport encryption scheme.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isProxyHeader: true,
  },
  'x-forwarded-host': {
    canonicalName: 'X-Forwarded-Host',
    category: 'PROXY_NETWORK',
    description: 'Identifies the original host requested by the client in the Host HTTP request header.',
    privacyImpact: 'Discloses requested hostname via proxy.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isProxyHeader: true,
  },
  'x-forwarded-port': {
    canonicalName: 'X-Forwarded-Port',
    category: 'PROXY_NETWORK',
    description: 'Identifies the destination port used to connect to the reverse proxy.',
    privacyImpact: 'Discloses client ingress port.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isProxyHeader: true,
  },
  'x-real-ip': {
    canonicalName: 'X-Real-IP',
    category: 'PROXY_NETWORK',
    description: 'Alternative reverse-proxy header containing the physical remote IP address of the connecting client.',
    privacyImpact: 'Directly discloses physical origin client IP address.',
    defaultStatus: 'WARNING',
    severity: 'high',
    riskPoints: 10,
    isProxyHeader: true,
  },
  'via': {
    canonicalName: 'Via',
    category: 'PROXY_NETWORK',
    description: 'Standard HTTP header added by intermediate proxies (forward and reverse) detailing gateway protocols and hostnames.',
    privacyImpact: 'Explicitly discloses existence and software of intermediate proxy gateways.',
    defaultStatus: 'WARNING',
    severity: 'medium',
    riskPoints: 8,
    isProxyHeader: true,
    isStandard: true,
    recommendation: 'Configure proxy to suppress or pseudonymize Via header signatures.',
  },
  'forwarded': {
    canonicalName: 'Forwarded',
    category: 'PROXY_NETWORK',
    description: 'RFC 7239 standardized header combining for, by, host, and proto proxy forwarding information.',
    privacyImpact: 'Discloses structured proxy forwarding routing parameters.',
    defaultStatus: 'WARNING',
    severity: 'high',
    riskPoints: 10,
    isProxyHeader: true,
    isStandard: true,
  },
  'cf-connecting-ip': {
    canonicalName: 'CF-Connecting-IP',
    category: 'PROXY_NETWORK',
    description: 'Cloudflare edge header providing the client IP address connected to Cloudflare reverse proxy edge.',
    privacyImpact: 'Exposes client origin IP to backend web servers.',
    defaultStatus: 'INFO',
    severity: 'medium',
    riskPoints: 0,
    isProxyHeader: true,
  },
  'cf-ray': {
    canonicalName: 'CF-Ray',
    category: 'PROXY_NETWORK',
    description: 'Cloudflare request identifier containing data center airport code and unique ray ID.',
    privacyImpact: 'Discloses geographical edge transit datacenter code.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isProxyHeader: true,
  },
  'cf-ipcountry': {
    canonicalName: 'CF-IPCountry',
    category: 'PROXY_NETWORK',
    description: 'Cloudflare country code header calculated at edge for visitor connection.',
    privacyImpact: 'Discloses edge-resolved visitor country.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isProxyHeader: true,
  },
  'true-client-ip': {
    canonicalName: 'True-Client-IP',
    category: 'PROXY_NETWORK',
    description: 'Akamai / Cloudflare enterprise header conveying the original client IP.',
    privacyImpact: 'Discloses origin visitor IP address.',
    defaultStatus: 'WARNING',
    severity: 'high',
    riskPoints: 10,
    isProxyHeader: true,
  },
  'x-client-ip': {
    canonicalName: 'X-Client-IP',
    category: 'PROXY_NETWORK',
    description: 'Non-standard proxy header conveying client IP address.',
    privacyImpact: 'Discloses client network endpoint.',
    defaultStatus: 'WARNING',
    severity: 'high',
    riskPoints: 10,
    isProxyHeader: true,
  },
  'fastly-client-ip': {
    canonicalName: 'Fastly-Client-IP',
    category: 'PROXY_NETWORK',
    description: 'Fastly CDN edge header conveying client IP.',
    privacyImpact: 'Discloses edge origin IP.',
    defaultStatus: 'INFO',
    severity: 'medium',
    riskPoints: 0,
    isProxyHeader: true,
  },

  // --- SECURITY & TRANSPORT ---
  'host': {
    canonicalName: 'Host',
    category: 'SECURITY_TRANSPORT',
    description: 'Specifies the host and port number of the server to which the request is being sent.',
    privacyImpact: 'Required HTTP/1.1 destination header.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'origin': {
    canonicalName: 'Origin',
    category: 'SECURITY_TRANSPORT',
    description: 'Indicates the origin (scheme, hostname, port) that initiated a cross-origin or POST request.',
    privacyImpact: 'Discloses referring web application origin.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'referer': {
    canonicalName: 'Referer',
    category: 'SECURITY_TRANSPORT',
    description: 'Contains the address of the previous web page from which a link was followed.',
    privacyImpact: 'Exposes referring page URL when navigating across origins.',
    defaultStatus: 'WARNING',
    severity: 'medium',
    riskPoints: 4,
    isStandard: true,
    recommendation: 'Configure browser Referrer-Policy or server policies to "strict-origin-when-cross-origin" or "no-referrer".',
  },
  'upgrade-insecure-requests': {
    canonicalName: 'Upgrade-Insecure-Requests',
    category: 'SECURITY_TRANSPORT',
    description: 'Signals to server that client prefers encrypted HTTPS connections over plaintext HTTP.',
    privacyImpact: 'Active transport security preference.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'sec-fetch-site': {
    canonicalName: 'Sec-Fetch-Site',
    category: 'SECURITY_TRANSPORT',
    description: 'Fetch Metadata request header indicating relationship between request initiator and requested resource (same-origin, same-site, cross-site, none).',
    privacyImpact: 'Provides request-context information that servers can use as part of CSRF and cross-site isolation defenses.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'sec-fetch-mode': {
    canonicalName: 'Sec-Fetch-Mode',
    category: 'SECURITY_TRANSPORT',
    description: 'Fetch Metadata request header indicating request mode (cors, navigate, no-cors, websocket).',
    privacyImpact: 'Discloses context of web resource invocation.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'sec-fetch-user': {
    canonicalName: 'Sec-Fetch-User',
    category: 'SECURITY_TRANSPORT',
    description: 'Fetch Metadata header indicating whether a navigation was triggered by explicit user gesture (clicks/taps).',
    privacyImpact: 'Distinguishes genuine user activation from automated or background scripts.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'sec-fetch-dest': {
    canonicalName: 'Sec-Fetch-Dest',
    category: 'SECURITY_TRANSPORT',
    description: 'Fetch Metadata header indicating the destination of the request (document, script, image, style, font, etc.).',
    privacyImpact: 'Discloses targeted browser rendering pipeline destination.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'authorization': {
    canonicalName: 'Authorization',
    category: 'SECURITY_TRANSPORT',
    description: 'Contains credentials for authenticating a user agent with a server.',
    privacyImpact: 'Contains highly sensitive session credentials or bearer tokens (strictly redacted).',
    defaultStatus: 'MASKED',
    severity: 'critical',
    riskPoints: 0,
    isSensitive: true,
    isStandard: true,
  },
  'proxy-authorization': {
    canonicalName: 'Proxy-Authorization',
    category: 'SECURITY_TRANSPORT',
    description: 'Contains credentials to authenticate a user agent with a proxy server.',
    privacyImpact: 'Contains sensitive proxy authentication credentials (strictly redacted).',
    defaultStatus: 'MASKED',
    severity: 'critical',
    riskPoints: 0,
    isSensitive: true,
    isStandard: true,
  },
  'x-requested-with': {
    canonicalName: 'X-Requested-With',
    category: 'SECURITY_TRANSPORT',
    description: 'Commonly sent by JavaScript AJAX frameworks or Android WebView applications.',
    privacyImpact: 'Discloses AJAX script execution or Android WebView wrapper package ID.',
    defaultStatus: 'INFO',
    severity: 'low',
    riskPoints: 1,
  },
  'x-csrf-token': {
    canonicalName: 'X-CSRF-Token',
    category: 'SECURITY_TRANSPORT',
    description: 'Security token used to prevent cross-site request forgery.',
    privacyImpact: 'Contains anti-CSRF token (masked).',
    defaultStatus: 'MASKED',
    severity: 'high',
    riskPoints: 0,
    isSensitive: true,
  },

  // --- CONTENT & NEGOTIATION ---
  'accept': {
    canonicalName: 'Accept',
    category: 'CONTENT_NEGOTIATION',
    description: 'Informs the server about MIME types the client is capable of processing and prioritizing.',
    privacyImpact: 'Indicates the response media types accepted by the client; quality weights apply only when q-values are actually present.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'accept-language': {
    canonicalName: 'Accept-Language',
    category: 'CONTENT_NEGOTIATION',
    description: 'Advertises client human language preferences and regional locales.',
    privacyImpact: 'Discloses spoken languages and geographic locale hints.',
    defaultStatus: 'INFO',
    severity: 'low',
    riskPoints: 2,
    isStandard: true,
    recommendation: 'Limit Accept-Language to a single generic language code to minimize locale entropy.',
  },
  'accept-encoding': {
    canonicalName: 'Accept-Encoding',
    category: 'CONTENT_NEGOTIATION',
    description: 'Advertises the content encoding algorithms (gzip, deflate, br, zstd) the client understands.',
    privacyImpact: 'Discloses supported compression algorithms.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'accept-charset': {
    canonicalName: 'Accept-Charset',
    category: 'CONTENT_NEGOTIATION',
    description: 'Advertises character encodings the client understands.',
    privacyImpact: 'Legacy character set disclosure.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'content-type': {
    canonicalName: 'Content-Type',
    category: 'CONTENT_NEGOTIATION',
    description: 'Indicates the media type of the resource in request body.',
    privacyImpact: 'Discloses payload format structure.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'content-length': {
    canonicalName: 'Content-Length',
    category: 'CONTENT_NEGOTIATION',
    description: 'Indicates the size of the request body in decimal number of octets.',
    privacyImpact: 'Discloses byte size of payload.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },

  // --- CACHING & STATE ---
  'cookie': {
    canonicalName: 'Cookie',
    category: 'CACHING_STATE',
    description: 'Contains stored HTTP cookies previously sent by the server with the Set-Cookie header.',
    privacyImpact: 'Contains session identifiers and tracking tokens (strictly redacted for data minimization).',
    defaultStatus: 'MASKED',
    severity: 'critical',
    riskPoints: 0,
    isSensitive: true,
    isStandard: true,
  },
  'set-cookie': {
    canonicalName: 'Set-Cookie',
    category: 'CACHING_STATE',
    description: 'Used by servers to send cookies to the user agent.',
    privacyImpact: 'Contains sensitive state tracking directives (strictly redacted).',
    defaultStatus: 'MASKED',
    severity: 'critical',
    riskPoints: 0,
    isSensitive: true,
    isStandard: true,
  },
  'cache-control': {
    canonicalName: 'Cache-Control',
    category: 'CACHING_STATE',
    description: 'Directives for caching mechanisms in both requests and responses (e.g. no-cache, max-age).',
    privacyImpact: 'Discloses client caching reload policy.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'pragma': {
    canonicalName: 'Pragma',
    category: 'CACHING_STATE',
    description: 'HTTP/1.0 legacy header used for backwards-compatible cache directives.',
    privacyImpact: 'Legacy cache control indicator.',
    defaultStatus: 'INFO',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'connection': {
    canonicalName: 'Connection',
    category: 'CACHING_STATE',
    description: 'Controls whether the network connection stays open after the current transaction finishes.',
    privacyImpact: 'TCP socket persistence directive.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'keep-alive': {
    canonicalName: 'Keep-Alive',
    category: 'CACHING_STATE',
    description: 'Allows sender to hint about how the connection may be used to set a timeout and maximum amount of requests.',
    privacyImpact: 'Socket reuse parameters.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'if-modified-since': {
    canonicalName: 'If-Modified-Since',
    category: 'CACHING_STATE',
    description: 'Conditional request header making request conditional on resource modification timestamp.',
    privacyImpact: 'Discloses when client last cached or accessed the target resource.',
    defaultStatus: 'INFO',
    severity: 'low',
    riskPoints: 1,
    isStandard: true,
  },
  'if-none-match': {
    canonicalName: 'If-None-Match',
    category: 'CACHING_STATE',
    description: 'Conditional request header making request conditional on entity tag (ETag). Can be misused for ETag tracking.',
    privacyImpact: 'Discloses cached ETag identifier; potential cross-request tracking mechanism.',
    defaultStatus: 'INFO',
    severity: 'low',
    riskPoints: 2,
    isStandard: true,
    recommendation: 'Ensure browser cache clearing removes stale conditional ETags.',
  },
  'te': {
    canonicalName: 'TE',
    category: 'CACHING_STATE',
    description: 'Specifies the transfer encodings the user agent is willing to accept.',
    privacyImpact: 'Chunked transfer capability hint.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
  'transfer-encoding': {
    canonicalName: 'Transfer-Encoding',
    category: 'CACHING_STATE',
    description: 'Specifies the form of encoding used to safely transfer the payload to the user.',
    privacyImpact: 'Transport chunking descriptor.',
    defaultStatus: 'SAFE',
    severity: 'info',
    riskPoints: 0,
    isStandard: true,
  },
};

/**
 * List of recommended privacy and security headers to audit for absence
 */
export const RECOMMENDED_MISSING_HEADERS: MissingHeaderDefinition[] = [
  {
    canonicalName: 'Sec-GPC',
    category: 'PRIVACY_TRACKING',
    importance: 'recommended',
    description: 'Global Privacy Control (GPC) header communicates an opt-out preference from data selling and cross-site tracking.',
    purpose: 'Signals user non-consent to third-party data sales and tracking under applicable privacy regulations (such as CCPA/CPRA).',
    recommendation: 'Enable Global Privacy Control (GPC) in your browser settings (Brave, Firefox, DuckDuckGo) or via privacy extensions.',
    benefit: 'Automated opt-out signal recognized by participating websites and frameworks in regulated jurisdictions.',
    checkCondition: (headers) => Boolean(headers['sec-gpc'] && headers['sec-gpc'] === '1'),
  },
];
